### PR TITLE
[macOS, CI] Build using macOS 10.13 SDK

### PR DESCRIPTION
**Pull request by nikolaykasyanov**

### CODE REVIEW

**Comment by psi29a** [comment]
Looks like there was a timeout on MacOS build, going to try again...

**Comment by nikolaykasyanov** [comment]
Looks like a legitimate build error, I’ll look into it.

**Comment by psi29a** [comment]
```
[ 93%] Linking CXX executable ../../OpenMW.app/Contents/MacOS/openmw
Undefined symbols for architecture x86_64:
  "_lzma_code", referenced from:
      _decode_frame in libavcodec.a(tiff.o)
  "_lzma_end", referenced from:
      _decode_frame in libavcodec.a(tiff.o)
  "_lzma_stream_decoder", referenced from:
      _decode_frame in libavcodec.a(tiff.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by nikolaykasyanov** [comment]
There was an issue with dependencies, I rebuilt & reupoaded them & now it's green.

**Comment by psi29a** [comment]
Thanks! :)
